/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.jetbrains.annotations.NotNull;

import java.io.File;
import java.io.IOError;
import java.io.IOException;

public class App {



    public static void main(String[] args) throws IOException {



        System.out.println(testFunction(args));

    }

    public static String testFunction(String[] argsPar) throws IOException {

        if (argsPar.length == 3) {
            String inputFilePath = argsPar[0];
            String outputFilePath = argsPar[1];

            Bitmap bitMap = new Bitmap(inputFilePath);

            if (argsPar[2].equals("convertImageToGray")) {
                bitMap.convertImageToGray();
            }
            if (argsPar[2].equals("mirrorImageVertically")) {
                bitMap.mirrorImageVertically();
            }
            if (argsPar[2].equals("mirrorImageHorizontally")) {
                bitMap.mirrorImageHorizontally();
            }

            bitMap.writeNewImage(outputFilePath);

            return (checkIfCreated(outputFilePath));
        } else {
            return ("args invalid");
        }


    }


    public static  String checkIfCreated(String outputFilePath){
        File outputFile = new File(outputFilePath);
        if (outputFile.exists()) {
            return "Done .. New image saved to " + outputFilePath;
        } else {
            return "Error: New image was not created.";
        }

}}
